/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface BasisTranscoder {
    'basisSrc': string;
    'height': number;
    'width': number;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLBasisTranscoderElement extends Components.BasisTranscoder, HTMLStencilElement {}
  var HTMLBasisTranscoderElement: {
    prototype: HTMLBasisTranscoderElement;
    new (): HTMLBasisTranscoderElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'basis-transcoder': HTMLBasisTranscoderElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface BasisTranscoder extends JSXBase.HTMLAttributes<HTMLBasisTranscoderElement> {
    'basisSrc'?: string;
    'height'?: number;
    'width'?: number;
  }
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'basis-transcoder': BasisTranscoder;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


