/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface BasisTranscoder {
    'basisSrc': string;
    'height': number;
    'width': number;
  }
}

declare global {


  interface HTMLBasisTranscoderElement extends Components.BasisTranscoder, HTMLStencilElement {}
  var HTMLBasisTranscoderElement: {
    prototype: HTMLBasisTranscoderElement;
    new (): HTMLBasisTranscoderElement;
  };
  interface HTMLElementTagNameMap {
    'basis-transcoder': HTMLBasisTranscoderElement;
  }
}

declare namespace LocalJSX {
  interface BasisTranscoder extends JSXBase.HTMLAttributes<HTMLBasisTranscoderElement> {
    'basisSrc'?: string;
    'height'?: number;
    'width'?: number;
  }

  interface IntrinsicElements {
    'basis-transcoder': BasisTranscoder;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


